### ISSUE TITLE
Using Python 3.7

### ISSUE THREAD

**Issue by doctorpangloss** [bitnami/bitnami-docker-spark#11]
**Description**

I'd like to use Python 3.7 and I just need help putting in the content on this line:

https://github.com/bitnami/bitnami-docker-spark/blob/f0b7ae9664961a533376dd62b15f1a46b55dfc3b/3/debian-10/Dockerfile#L13

What should go here to use 3.7 instead of 3.6?

I observe only lines for 2.7 and 3.6:

https://grep.app/search?q=/opt/bitnami/scripts/libcomponent.sh%20%26%26%20component_unpack%20%22python%22%20

**Comment by rafariossaa** [comment]
Hi,
  In this case you can pick the checksum and version from here: 
  https://github.com/bitnami/bitnami-docker-python/blob/master/3.7/debian-10/Dockerfile

**Comment by doctorpangloss** [comment]
Looks good thank you
