### ISSUE TITLE
Support for Hadoop 3.2

### ISSUE THREAD

**Issue by michaelbpalmer** [bitnami/bitnami-docker-spark#12]
**Description**

Spark 3.0 supports two prebuilt Hadoop configurations -- Hadoop 2.7 and Hadoop 3.2. This image appears to install the Hadoop 2.7 version of Spark, and I don't see any way to configure this to install the Hadoop 3.2 version.

If this is currently supported, can you show me how? If not, is it possible to add this support? Note: We consume this using the Helm chart, so ideally the Hadoop version would be a config option that we could supply when installing the Helm chart.

**Comment by beltran-rubo** [comment]
Hi @michaelbpalmer 

Thanks for your feedback! We already have an internal task to upgrade Spark to use Hadoop 3.x reported at https://github.com/bitnami/bitnami-docker-spark/issues/3#issuecomment-651916594 It could take some weeks to have it done.

**Comment by michaelbpalmer** [comment]
Thanks, @beltran-rubo. I'll follow that issue for updates. In the interim, I've got something working locally that's unblocked me.

**Comment by beltran-rubo** [comment]
This was now fixed and it uses Hadoop 3.x.

This section shows how to modify to other version if needed. https://github.com/bitnami/bitnami-docker-spark#using-a-different-version-of-hadoop-jars
