### ISSUE TITLE
Permission Error on installing python packages through pip

### ISSUE THREAD

**Issue by sartaaj13** [bitnami/bitnami-docker-spark#14]
**Description**

**Steps to reproduce the issue:**

1. Run docker-compose up command
2. Bash into the Docker Container using **docker exec -it [id] bash**
3. Try to run **pip install numpy**

**Got the following Result**
```
WARNING: The directory '/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting numpy
  Downloading numpy-1.19.2-cp36-cp36m-manylinux2010_x86_64.whl (14.5 MB)
     |################################| 14.5 MB 3.0 MB/s
Installing collected packages: numpy
### ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/.local' Check the permissions.
```

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by carrodher** [comment]
Hi, following the best practices for developing containers, the spark container is a [non-root container](https://github.com/bitnami/bitnami-docker-spark#why-use-a-non-root-container), that means the container user is not a privileged user being not possible to install packages.

There are several ways to run the container as root, but this is not the default configuration:

- **Option 1:** Build a new image removing the `USER: 1001` directive from the Dockerfile, with this method the container is going to be a root container. Then you need to use this image in your _docker-compose.yaml_
- **Option 2**: Adding `user: root` in the _docker-compose.yaml_, using this approach the container is going to be executed with root user without built a new image:
```diff
services:
  spark:
    image: docker.io/bitnami/spark:3-debian-10
+   user: root
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
```

Using both approaches the container is executed as root and you should be able to install packages:
```
root@c88cfa6de101:/opt/bitnami/spark# pip install numpy
Collecting numpy
  Downloading numpy-1.19.2-cp36-cp36m-manylinux2010_x86_64.whl (14.5 MB)
     |################################| 14.5 MB 10.7 MB/s
Installing collected packages: numpy
Successfully installed numpy-1.19.2
```

**Comment by sartaaj13** [comment]
Thanks @carrodher for the response. Second option worked for me 👍

**Comment by lucas-cabello** [comment]
Hi, even though @carrodher suggestions works, Which would be the correct way to submit a python spark script using external libraries?

**Comment by carrodher** [comment]
I'm sorry but I am not a spark user, how do you usually do that in a non-bitnami or non-container spark installation? In this case, you can mount any directory to the container by using the docker-compose, access the container, and execute any command. In the same way, you can extend this image by building a custom one.

Also in the README, you can find more configuration options like mounting different config files, installing jars, using env. variables, etc
