### ISSUE TITLE
spark 2.4.7 is available

### ISSUE THREAD

**Issue by mike-boost** [bitnami/bitnami-docker-spark#16]
The Spark 2.4.7 is available at Sep 12 2020 .
Will the bitnami  robot build it automatically or any mannual trigger?

**Comment by dani8art** [comment]
Hi @mike-boost, thank you for opening this issue.

We are currently supporting the new versions for Spark branch 3.x only, aren't these versions suitable for you?

**Comment by nstdio** [comment]
Hi @dani8art , we are using Apache Livy to spawn jobs on spark. It seems that the last version of Livy does not support Scala `2.12` which is compile target for Spark 3.x line.

**Comment by dani8art** [comment]
We are so sorry but we only support the version 3 branch since 25 Jun 2020 see https://github.com/bitnami/bitnami-docker-spark/releases/tag/3.0.0-debian-10-r0, however, you could use the last `bitnami/spark:2` that still exists in dockerhub.
