### ISSUE TITLE
adoptjdk11 image

### ISSUE THREAD

**Issue by abhinavthakur07** [bitnami/bitnami-docker-spark#17]
**Description**
where cani found image with adoptjdk11 image . currently using image having java8
  registry: docker.io
  repository: bitnami/spark
  tag: 3.0.1-debian-10-r0

https://github.com/bitnami/charts/blob/master/bitnami/spark/values.yaml

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by javsalgar** [comment]
Hi,

I'm afraid we're not offering a Spark image with Java 11 right now. For the time being, you would need to create a custom image

https://github.com/bitnami/bitnami-docker-spark/blob/master/3/debian-10/Dockerfile

Replace the line installing Java 8 with one installing Java 11

Replace this

```
RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "java" "1.8.265-0" --checksum 6c85e8df954fca444f2471195524db015ec24a67e42f43579401f2adb5189cb8

```

With this

```
RUN wget -nc -P /tmp/bitnami/pkg/cache/ https://downloads.bitnami.com/files/stacksmith/java-11.0.8-1-linux-amd64-debian-10.tar.gz && \
    echo "811b17aa00d6687a6c6e555a4131e585a1a2d24b7fdaa2e5d67f4baea2165aa0  /tmp/bitnami/pkg/cache/java-11.0.8-1-linux-amd64-debian-10.tar.gz" | sha256sum -c - && \
    tar -zxf /tmp/bitnami/pkg/cache/java-11.0.8-1-linux-amd64-debian-10.tar.gz -P --transform 's|^[^/]*/files|/opt/bitnami|' --wildcards '*/files' && \
    rm -rf /tmp/bitnami/pkg/cache/java-11.0.8-1-linux-amd64-debian-10.tar.gz
```

**Comment by abhinavthakur07** [comment]
Hi , Thanks i will try with this

**Comment by abhinavthakur07** [comment]
If anybody trying to follow this step. Add these line as well to avoid this error /bin/sh: 1: wget: not found

RUN  apt-get update \
    && apt-get install -y wget \
     && rm -rf /var/lib/apt/lists/*

**Comment by javsalgar** [comment]
Good to know that it worked! And thanks for the tip!
