### ISSUE TITLE
Container does not respect SIGTERM

### ISSUE THREAD

**Issue by software-opal** [bitnami/bitnami-docker-spark#2]
**Description**

Trying to stop the container by pressing `Ctrl-C` in a docker run command, or using `docker kill -s TERM` does not cause the container to gracefully exit.

**Steps to reproduce the issue:**

1. Run the image: `docker run bitnami/spark:2.4.4`
2. Try to exit using Ctrl-C

**Describe the results you received:**

The container does not stop after pressing Ctrl-C

**Describe the results you expected:**

The spark process should start gracefully shutting down and the container should exit.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 37
  Running: 3
  Paused: 0
  Stopped: 34
 Images: 433
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.943GiB
 Name: docker-desktop
 ID: GYO6:4U2Y:CDAY:T5TN:7VZQ:UBHB:UPAC:MN6H:EPPA:H5ER:JGEX:O7ZN
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 66
  Goroutines: 101
  System Time: 2020-02-11T04:21:57.6292578Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

This is running on Docker for Mac.

**Comment by carrodher** [comment]
Hi, thanks for reporting it. I was able to reproduce the issue, `CTRL-C` doesn't work to stop the container.

I was able to workaround the issue using `docker stop` in a different terminal/tab:
```bash
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
ff40e85c1e82        bitnami/spark       "/entrypoint.sh /run…"   44 seconds ago      Up 43 seconds                           recursing_pare

$ docker stop ff40e85c1e82
ff40e85c1e82
```

I will continue investigating the `CTRL-C` issue, but I hope that in the meantime the workaround works for you.

**Comment by p3t3rix** [comment]
Still an issue.

**Comment by dgomezleon** [comment]
Hi,

This is due to problems signaling PID 1 process. [Here](https://engineeringblog.yelp.com/2016/01/dumb-init-an-init-for-docker.html#process-behavior-inside-docker-containers) you can find a really interesting article about this issue.  

You can add `-t` to the docker run command, which will attach a pseudo-TTY. As a workaround, using `-t` and `-i` allows `Control-C` to terminate the container, and `Control-P Control-Q` to detach without terminating it.
