### ISSUE TITLE
Error when running spark-submit with Minikube/Kubernetes

### ISSUE THREAD

**Issue by ryanpoplin** [bitnami/bitnami-docker-spark#21]
Hey Bitnami Folks,

I'm using this image: https://hub.docker.com/layers/bitnami/spark/3.0.1-debian-10-r65/images/sha256-c81e869ccca19d94ffaf4bdc7fee9e8011119fee9ef849d7aa437f611a4774f8?context=explore. 

I run locally with a Spark 3.0.1 build as the Spark client for 'spark-submit' to Kubernetes like so: `./bin/spark-submit --master k8s://https://127.0.0.1:<port> --deploy-mode cluster --conf spark.kubernetes.container.image=bitnami/spark:3.0.1-debian-10-r65 --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark --conf spark.executor.instances=2 --class org.apache.spark.examples.SparkPi local:///examples/jars/spark-examples_2.12-3.0.1.jar 1000`

I am getting an 'Error' failure status on the job in the cluster. When I check the logs like so `kubectl logs org-apache-spark-examples-sparkpi-xyz-driver`, I get this back:

 10:27:12.01
 10:27:12.01 Welcome to the Bitnami spark container
 10:27:12.01 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-spark
 10:27:12.01 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-spark/issues
 10:27:12.02

/opt/bitnami/scripts/spark/entrypoint.sh: line 32: exec: driver: not found

Any guidance would be helpful!

Thanks,

RP

**Comment by dani8art** [comment]
Hi @ryanpoplin, thank you so much for your feedback!

Our image and chart only support [standalone spark cluster](https://spark.apache.org/docs/1.1.0/spark-standalone.html) type at this moment. You would need to use a submit command to fit this kind of clusters, an example could be

```console
./bin/spark-submit --master spark://<YOUR_MASTER_IP>:<PORT> --deploy-mode cluster --class org.apache.spark.examples.SparkPi examples/jars/spark-examples_2.12-3.0.1.jar 1000
```

- Take into account `YOUR_MASTER_IP` needs to be resolvable by all the nodes inside the cluster, if you pass `127.0.0.1` it will fail since nodes will try to connect to its local loopback IP.

**Comment by warichet** [comment]
Hello,
i have modified the entrypoint.sh to deal with driver argument.
That's ugly but it seems work.

Best regards
Sébastien

```
#!/bin/bash

# echo commands to the terminal output
set -ex
set -o errexit
set -o nounset
set -o pipefail

# Load libraries
. /opt/bitnami/scripts/libbitnami.sh
. /opt/bitnami/scripts/libspark.sh

# Load Spark environment variables
eval "$(spark_env)"

print_welcome_page

if [ ! $EUID -eq 0 ] && [ -e "$LIBNSS_WRAPPER_PATH" ]; then
    echo "spark:x:$(id -u):$(id -g):Spark:$SPARK_HOME:/bin/false" > "$NSS_WRAPPER_PASSWD"
    echo "spark:x:$(id -g):" > "$NSS_WRAPPER_GROUP"
    echo "LD_PRELOAD=$LIBNSS_WRAPPER_PATH" >> "$SPARK_CONFDIR/spark-env.sh"
fi

if [[ "$*" = "/opt/bitnami/scripts/spark/run.sh" ]]; then
    info "** Starting Spark setup **"
    /opt/bitnami/scripts/spark/setup.sh
    info "** Spark setup finished! **"
fi

case "$1" in
  driver)
    shift 1
    CMD=(
      "$SPARK_HOME/bin/spark-submit"
      --conf "spark.driver.bindAddress=$SPARK_DRIVER_BIND_ADDRESS"
      --deploy-mode client
      "$@"
    )
    ;;
  *)
    echo "Non-spark-on-k8s command provided, proceeding in pass-through mode..."
    CMD=("$@")
    ;;
esac

echo ""
exec "${CMD[@]}"
```
