### ISSUE TITLE
How to connect bitnami/spark cluster with Jupyter Hub / Notebook ? 

### ISSUE THREAD

**Issue by msinha251** [bitnami/bitnami-docker-spark#22]
**Description**

**Steps to reproduce the issue:**

1. Helm install bitnami/spark [values.service.type = LoadBalancer]
2. Deploy Jupyter hub or jupyter nodebook on Kubernetes as LoadBalancer IP
3. On Jupyter notebook or hub try to connect spark cluster

**Describe the results you received:**

I can connect to the spark cluster with spark URL (spark://spark3-master-0.spark3-headless.default.svc.cluster.local:7077). But post that none of the pyspark fuctions are running. like spark.count etc.
**Describe the results you expected:**
I want to execute all spark jobs from Jupyter notebook and Hub.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by marcosbc** [comment]
Hi @msinha251,

> 3. On Jupyter notebook or hub try to connect spark cluster
>...
>  I want to execute all spark jobs from Jupyter notebook and Hub.

Could you share more information on how specifically you're connecting to the Spark cluster and running the jobs?

Note that we are not familiar with Jupyter Hub/Notebook, so if you could provide the specific steps to reproduce this issue in Jupyter Hub, after deploying the official Helm chart, it would be helpful for us to investigate and provide an answer of what is happening.

**Comment by msinha251** [comment]
I am trying to run simple code (given below ) from Jupyter Notebook:
```
import pyspark
sc = pyspark.SparkContext(appName="test", master="<SPARK CLUSTER URL Copied FROM SPARK WEBUI>")
sc.range(100).count()
```
Post executing the above three lines I can see the app (test) on spark UI under running applications but it stuck forever and never come out, until explicitly killing or restarting the session.

Jupyter notebook logs saying "Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources"

Jupyter notebook is deployed as a separate deployment in kubernetes and exposed as load balancer service.

Hope it helps to debug.

**Comment by marcosbc** [comment]
Hi @msinha251, I was able to reproduce some issues with Jupyter Notebook (on k8s) + Spark:

```
Exception                                 Traceback (most recent call last)
<ipython-input-2-39291df0cd49> in <module>
      1 import pyspark
----> 2 sc = pyspark.SparkContext(appName="test", master="spark://myspark-master-0.myspark-headless.default.svc.cluster.local:7077")
      3 sc.range(100).count()

/opt/conda/lib/python3.7/site-packages/pyspark/context.py in __init__(self, master, appName, sparkHome, pyFiles, environment, batchSize, serializer, conf, gateway, jsc, profiler_cls)
    131                 " is not allowed as it is a security risk.")
    132 
--> 133         SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
    134         try:
    135             self._do_init(master, appName, sparkHome, pyFiles, environment, batchSize, serializer,

/opt/conda/lib/python3.7/site-packages/pyspark/context.py in _ensure_initialized(cls, instance, gateway, conf)
    323         with SparkContext._lock:
    324             if not SparkContext._gateway:
--> 325                 SparkContext._gateway = gateway or launch_gateway(conf)
    326                 SparkContext._jvm = SparkContext._gateway.jvm
    327 

/opt/conda/lib/python3.7/site-packages/pyspark/java_gateway.py in launch_gateway(conf, popen_kwargs)
    103 
    104             if not os.path.isfile(conn_info_file):
--> 105                 raise Exception("Java gateway process exited before sending its port number")
    106 
    107             with open(conn_info_file, "rb") as info:

Exception: Java gateway process exited before sending its port number
```

However, that error happens because Java (or JRE) is missing in the container. This can be easily reproduced like this:

```console
$ kubectl run myspark-client --restart='Never' --image docker.io/bitnami/minideb:latest --namespace default --command -- sleep infinity
$ kubectl exec -ti pod/myspark-client bash -c "apt-get update && apt-get install python3 python3-pip && pip install pyspark"
$ kubectl exec -ti pod/myspark-client python
```

And then execute the Python code you showed above:

```python
import pyspark
sc = pyspark.SparkContext(appName="test", master="spark://myspark-master-0.myspark-headless.default.svc.cluster.local:7077")
sc.range(100).count()
```

To fix that, you can install Java via `default-jre`:

```
$ kubectl exec -ti pod/myspark-client apt-get install default-jre
```

Does it solve your issue? Or were you facing another problem? Please share the specific errors so we can be more helpful.

**Comment by msinha251** [comment]
Thanks @marcosbc for prompt response.

Unfortunately I am not facing this issue of java instead I am able to connect to the spark cluster by executing below two lines. And also I can see the application (test) under running applications of spark UI.
```
import pyspark
sc = pyspark.SparkContext(appName="test", master="<SPARK CLUSTER URL Copied FROM SPARK WEBUI>")

```
But as soon as I execute below line or any spark operation. It hangs forever...
`sc.range(100).count()`

And jupyter notebook log says below line until I explicitly kill that job or restart the jupyter session.
`Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources` 

For more details, I am using "jupyter/all-spark-notebook" docker image which has all the dependency for spark.

I hope you can reproduce it in your environment by just deploying below two deployments on k8s:

- bitnami/spark cluster (helm install)
- jupyter notebook deployment by using "jupyter/all-spark-notebook" docker image.

If you have any alternate approach for connecting spark cluster from external jupyter notebook, I would be happy to look at that as well.

Thanks

**Comment by marcosbc** [comment]
Hi @msinha251, that seems to be related with this GitHub issue: https://github.com/bitnami/bitnami-docker-spark/issues/18

In particular, if you check [dani8art's comment](https://github.com/bitnami/bitnami-docker-spark/issues/18#issuecomment-700628676) you'll see that it is necessary to configure some additional stuff before running the Spark job.

**Comment by msinha251** [comment]
Thanks @marcosbc  it worked.

**Comment by JavadHosseini** [comment]
I have the same environment and everything works fine, but I want to add a pyspark kernel to jupyterhub so users don't have to create spark context themselves. I tried this json file but no luck.
```
{
 "argv": ["python", "-m", "ipykernel_launcher", "-f", "{connection_file}"],
 "env": {
  "PYSPARK_PYTHON": "/usr/bin/python3",
  "SPARK_HOME": "/opt/bin/spark-3.1.2-bin-hadoop3.2",
  "PYTHONPATH": "/opt/bin/spark-3.1.2-bin-hadoop3.2/python/lib/py4j-0.10.9-src.zip:/opt/bin/spark-3.1.2-bin-hadoop3.2/python/",
  "PYTHONSTARTUP": "/opt/bin/spark-3.1.2-bin-hadoop3.2/python/pyspark/shell.py",
  "PYSPARK_SUBMIT_ARGS": "--total-executor-cores 10 --master spark://10.233.59.159:7077 pyspark-shell --conf spark.driver.host=192.168.201.229 --conf spark.driver.bindAddress=0.0.0.0 --conf spark.submit.deployMode=client"
 },
 "display_name": "PySpark",
 "language": "python"
}
```
I can see that a new kernel has been added to jupyter hub but when I run `sc` it return an empty string which it should return spark context info if everything was ok.
