### ISSUE TITLE
Install Spark in IBM Cloud

### ISSUE THREAD

**Issue by datta-TG** [bitnami/bitnami-docker-spark#24]
Apache Spark is a Big Data solution oriented to data processing. This documentation will teach you how to install Spark in the IBM Cloud using the Kubernetes Cluster Service.

## Pre-requisites

You must have an account created in IBM Cloud. The account needs to either be *Pay-As-You-Go* or *Subscription*. Click [here](https://cloud.ibm.com/docs/account?topic=account-accounts "here") to read more.
If you have a Lite account, you can upgrade it. Click [here](https://cloud.ibm.com/docs/account?topic=account-account-getting-started#account-gs-upgrade "here") to learn how to upgrade.

## Step 1: Provision Kubernetes Cluster

* Click on the search section at the top of the main page, type Kubernetes, and then choose Kubernetes Service.

![Kubernetes1](https://user-images.githubusercontent.com/70336951/105732644-ac477380-5efe-11eb-83e4-92471ac878bc.png)

* In the new window, select between the free and standard type under "Pricing plan". Once selected, click on create.

![KubernetesPaid1](https://user-images.githubusercontent.com/70336951/105732663-b0739100-5efe-11eb-89f0-7fd98dd21250.PNG)

We'll choose the Standard Plan for this documentation as the Free Plan may fall short of resources when deploying your pods. We highly recommend using a Standard Plan with the hardware that suits you the best. If you're selecting the Standard Plan, please make sure you select the adequate requirements as the following ones are selected as default for the tutorial,

* Select your Kubernetes Version to be the latest available or the required one by your application. In this example, we have set it to be '1.18.13'.
* Select Infrastructure as 'Classic'.
* Leave Resource Group to 'Default'.
* Select Geography to the one that suits you better or that fits your infrastructure.
* Select Availability to be 'Single Zone' or 'Multi Zone' depending on your needs.
* Select a Worker Zone that suits you better or that fits your infrastructure.

![KubernetesPaid2](https://user-images.githubusercontent.com/70336951/105732676-b5384500-5efe-11eb-8399-00386368fd00.PNG)

* Select the number of workers in Worker Pool.
* Give your Worker Pool a name.
* Leave the Encrypt Local Disk option 'On'
* Choose 'Both private and public endpoints' on Master Service Endpoint

![KubernetesPaid4](https://user-images.githubusercontent.com/70336951/105732700-bb2e2600-5efe-11eb-9d95-21b6912dd7d6.PNG)

* Give your cluster a name in 'cluster-name'
* Provide the tags to your cluster and click on Create.

![KubernetesPaid5](https://user-images.githubusercontent.com/70336951/105732718-bf5a4380-5efe-11eb-8a5b-6c3e93e7437d.PNG)

Wait a few minutes while your cluster is deployed.

![KubernetesPaid3](https://user-images.githubusercontent.com/70336951/105732740-c5e8bb00-5efe-11eb-8df3-90382227dff2.PNG)

The following checkmark and the word 'normal' will appear once the Kubernetes Cluster is deployed. You can check it under your cluster section which is located in your *Resources List*.

![KubernetesPaid6](https://user-images.githubusercontent.com/70336951/105732753-caad6f00-5efe-11eb-802e-ae7fa76177e4.PNG)

## Step 2:  Deploy IBM Cloud Block Storage plug-in

* Click on the search section at the top of the main page, select IBM Cloud Block Storage, and click on it.

![StoragePaid1](https://user-images.githubusercontent.com/70336951/105732784-d1d47d00-5efe-11eb-824d-d6af2e823cfb.PNG)

* A new window opens, select the cluster and enter the name you want for this workspace, in this case, it will be called _storage-example_, accept the terms, click *Install* and wait a few minutes.

![StoragePaid2](https://user-images.githubusercontent.com/70336951/105732799-d6993100-5efe-11eb-8b48-ecf942111907.PNG)

## Step 3: Install Spark

* Click on the search section at the top of the main page, type Spark, and click on it.

![Spark1](https://user-images.githubusercontent.com/70336951/105732827-de58d580-5efe-11eb-80dc-cc16660301b6.PNG)

* A new window opens, select the cluster and enter the name you want for the Spark workspace or select an exist workspace, in this case, we'll create a new one and it will be called _spark-example_, accept the terms and click on *Install*. You can modify the different installation parameters at the bottom. We will leave them by default as shown below, but you can read more about setting up the parameters [here](https://cloud.ibm.com/catalog/content/spark#about "here").

![Spark2](https://user-images.githubusercontent.com/70336951/105732845-e44eb680-5efe-11eb-8c51-c9c2844de658.PNG)

## Step 4: Verify Installation

* Go to *Resources List* in the Left Navigation Menu and click on *Kubernetes*.

![test1](https://user-images.githubusercontent.com/70336951/105732871-ec0e5b00-5efe-11eb-9138-168b33e14527.png)

* Click the *Actions* button and select *Web terminal*.

![test2](https://user-images.githubusercontent.com/70336951/105732889-efa1e200-5efe-11eb-89d8-207367329a95.PNG)

* A window opens to install the web terminal, click on install and wait a few minutes. The window will pop up at the buttom If the web terminal is already installed.

![test3](https://user-images.githubusercontent.com/70336951/105732902-f597c300-5efe-11eb-93d7-89021ca77ab9.PNG)

![test7](https://user-images.githubusercontent.com/70336951/105732910-f7fa1d00-5efe-11eb-8472-d1c26498f666.PNG)

* Once you have installed the terminal, open it, select web terminal, and type the following command. It will show you the workspaces of your cluster. You can see *spark-example* is now active.

`$ kubectl get ns`

![testspark1](https://user-images.githubusercontent.com/70336951/105732936-ff212b00-5efe-11eb-9d6d-1940322b798d.PNG)

* You can then obtain more data about the service and it's pods.

`$ kubectl get pod -n NAMESERVICE -o wide`

![testspark2](https://user-images.githubusercontent.com/70336951/105732951-02b4b200-5eff-11eb-99d9-b96e8aab0179.PNG)

`$ kubectl get service -n NAME SERVICE`

![testspark3](https://user-images.githubusercontent.com/70336951/105732972-07796600-5eff-11eb-8408-2a46e1244615.PNG)

* Select the master pod within your service using bash.

`$ kubectl exec --stdin --tty PODNAME -n NAMESPACE -- /bin/bash`

![testspark4](https://user-images.githubusercontent.com/70336951/105732998-0ba58380-5eff-11eb-88a9-56fd289b65e8.PNG)

* And finally, check if Spark is correctly installed checking and using the examples it has for different languages including Java, Python and Scala. In this case we will check the examples for Python. Just navigate to the following path:

`cd examples/src/main/python `

![testspark5](https://user-images.githubusercontent.com/70336951/105733019-1102ce00-5eff-11eb-9b15-70c7624f3c63.PNG)

* You can also read the Spark official documentation on how to operate with the tool using Kubernetes [here](https://spark.apache.org/docs/latest/running-on-kubernetes.html "here").

You have finished the installation, enjoy your Spark installation!

**Comment by carrodher** [comment]
Thanks for the info. As it seems that there is no issue we should take action and everything works properly, I am going to mark this issue as “Closed” so it can be used by other users looking for information as if it were documentation
