### ISSUE TITLE
KerberosAuthException during spark submit

### ISSUE THREAD

**Issue by mst94** [bitnami/bitnami-docker-spark#27]
I dont think it is a bug, but i cannot make my spark submit running.

I have containerized my spark application. My docker image which base image is your spark image contains an own spark-submit-script which is the entrypoint and also mounts my uber jar. But submission is not successful, a KerberosAuthException occures but I do not want to use Kerberos and can't remember that I enabled it. Is there a way to disable kerberos?

Exception:  

```
sparkstreamingetaprediction | 21/03/01 16:51:01 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
sparkstreamingetaprediction | Exception in thread "main" org.apache.hadoop.security.KerberosAuthException: failure to login: javax.security.auth.login.LoginException: java.lang.NullPointerException: invalid null input: name
sparkstreamingetaprediction |   at com.sun.security.auth.UnixPrincipal.<init>(UnixPrincipal.java:71)
sparkstreamingetaprediction |   at com.sun.security.auth.module.UnixLoginModule.login(UnixLoginModule.java:133)
sparkstreamingetaprediction |   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sparkstreamingetaprediction |   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sparkstreamingetaprediction |   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
sparkstreamingetaprediction |   at java.lang.reflect.Method.invoke(Method.java:498)
sparkstreamingetaprediction |   at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755)
sparkstreamingetaprediction |   at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
sparkstreamingetaprediction |   at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
sparkstreamingetaprediction |   at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
sparkstreamingetaprediction |   at java.security.AccessController.doPrivileged(Native Method)
sparkstreamingetaprediction |   at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
sparkstreamingetaprediction |   at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
sparkstreamingetaprediction |   at org.apache.hadoop.security.UserGroupInformation$HadoopLoginContext.login(UserGroupInformation.java:1926)
sparkstreamingetaprediction |   at org.apache.hadoop.security.UserGroupInformation.doSubjectLogin(UserGroupInformation.java:1837)
sparkstreamingetaprediction |   at org.apache.hadoop.security.UserGroupInformation.createLoginUser(UserGroupInformation.java:710)
sparkstreamingetaprediction |   at org.apache.hadoop.security.UserGroupInformation.getLoginUser(UserGroupInformation.java:660)
sparkstreamingetaprediction |   at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:571)
sparkstreamingetaprediction |   at org.apache.spark.util.Utils$.$anonfun$getCurrentUserName$1(Utils.scala:2414)
sparkstreamingetaprediction |   at scala.Option.getOrElse(Option.scala:189)
```

(splitted)

Spark-submit script:
```
spark-submit --class org.demo.myapp \
--master spark://spark:7077 
--deploy-mode cluster 
--conf spark.authenticate=false 
--conf spark.jars.ivy=/opt/bitnami/spark/ivy 
/opt/sparkbin/myapp.jar`
```

Thanks in advance

**Comment by juan131** [comment]
Hi @mst94 

Are you using your "custom Spark image" only to act as a client? Or are you also using your custom image to bootstrap the Spark server/cluster?

**Comment by mst94** [comment]
Hi @juan131 ,

thanks for the reply. I am using a spark cluster consisting of a spark master and two spark workers (all bitnami spark images), which is started via docker compose and operates in the same network as my custom image. I use my custom image only as a way to use the spark shell for submitting.

**Comment by juan131** [comment]
Thanks for the details @mst94 

Did you create your Spark cluster enabling RPC authentication? Find more information in the link below:

- https://github.com/bitnami/bitnami-docker-spark#security

**Comment by mst94** [comment]
Hello @juan131 ,

all security options (RPC, SSL) are disabled at the moment and the container is running as root. Here is the piece of the docker-compose file for my cluster (sorry, code listing seems not to work for this piece):

spark:
    image: docker.io/bitnami/spark:3-debian-10
    user: root
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
    volumes:
      - ./jars_dir:/opt/bitnami/spark/ivy:z
      - ./apps:/opt/bitnami/spark-apps
    networks:
      - sharednw
      
  spark-worker-1:
    image: docker.io/bitnami/spark:3-debian-10
    user: root
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./jars_dir:/opt/bitnami/spark/ivy:z
      - ./apps:/opt/bitnami/spark-apps
    networks:
      - sharednw
      
  spark-worker-2:
    image: docker.io/bitnami/spark:3-debian-10
    user: root
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./jars_dir:/opt/bitnami/spark/ivy:z
      - ./apps:/opt/bitnami/spark-apps
    networks:
      - sharednw

**Comment by juan131** [comment]
Hi @mst94 

I've been reviewing the default image, and I can' find anyplace where we're enabling Kerberos authentication. Is it possible that any of your custom jars are enforcing this authentication?

**Comment by mst94** [comment]
Hi @juan131,

I could figure out the problem. I had to add the root user (and the root usergroup) to the settings of my jib gradle plugin with which I am creating my custom submit image. 

So it was not a problem of your image.

Thanks for your time and help, I close this issue.

**Comment by alexeyostrovsky-rabove** [comment]
> Hi @juan131,
> 
> I could figure out the problem. I had to add the root user (and the root usergroup) to the settings of my jib gradle plugin with which I am creating my custom submit image.
> 
> So it was not a problem of your image.
> 
> Thanks for your time and help, I close this issue.

@mst94 
Can you please explain what kind of settings you added?
I am having similar issues but with other images. I am able to run spark-submit manual from PC but when when it called by airflow server inside it's image spark-submit failing with KerberosAuthException.
May be thing that you added in your case will give some clue for mine.

**Comment by mst94** [comment]
Hi,

that were my settings inside the gradle.build file:


....
 container {
        entrypoint = ["bash", "/opt/script/my-spark-submit.sh", "com.my.mainClassName",
                      "/opt/bitnami/spark-apps/my-app-1.0-SNAPSHOT.jar"]
        environment = ["SPARK_MASTER": "spark://spark:7077"]
        user = 'root:root'
    }
...

Of course defining a root user might not be the proper way for production use, just for experimental use.

**Comment by ebuildy** [comment]
``spark`` user should be added into the ``/etc/passwd`` file
