### ISSUE TITLE
Add GraphFrames package 

### ISSUE THREAD

**Issue by warichet** [bitnami/bitnami-docker-spark#29]
Hello,
i planed to used "graphframes" in bitnami spark container.

**I try to add jar file in container using Dockerfile:**
FROM docker.io/bitnami/spark:3-debian-10
....
COPY graphframes-0.8.1-spark3.0-s_2.12.jar /opt/bitnami/spark/jars/graphframes-0.8.1-spark3.0-s_2.12.jar
....
The docker command
docker exec spark_spark_1 ls -ltr /opt/bitnami/spark/jars/ | grep graphframes
give
-rw-r--r-- 1 root root   248133 Mar  8 08:59 graphframes-0.8.1-spark3.0-s_2.12.jar
But i have an error when i submit my application
ModuleNotFoundError: No module named 'graphframes'

**I try to add package in submit command**
spark-submit \
    --master spark://0.0.0.0:7077 \
    --deploy-mode client \
    --packages graphframes:graphframes:0.8.1-spark3.0-s_2.12 \
    --conf spark.cores.max=1 \
    --conf spark.executor.memory=1g \
	/opt/bitnami/spark/graph_generator.py
I have an error, according to read.me it is not the right way to add package with bitnami.
Exception in thread main java.io.FileNotFoundException: /opt/bitnami/spark/.ivy2/cache/resolved-org.apache.spark-spark-submit-parent-aae13c04-40f1-469e-8e68-2cfb56fbaf62-1.0.xml (No such file or directory)

My question is what is the best way to install graphframes in bitnami container?

Thanks for your attention
Sébastien

**Comment by warichet** [comment]
Resolved 

In docker-compose.yml:
Add volumes for ivy directory
    volumes:
      - ./master-ivy-jars:/opt/bitnami/spark/ivy:z

In Dockerfile:
Install numpy needed by Graphframes
USER root
RUN pip install numpy
USER 1001

In submit:
Add graphframes package
docker exec spark_spark_1 \
    spark-submit \
      .....
      --conf spark.jars.ivy=/opt/bitnami/spark/ivy \
      --conf spark.jars=/opt/bitnami/spark/jars \
      --packages graphframes:graphframes:0.8.1-spark3.0-s_2.12 \
      ....

It is works

**Comment by marcosbc** [comment]
Awesome, thanks for sharing!
