### ISSUE TITLE
hadoop-aws and aws-java-sdk jars added in 2.4.5-debian-10-r49 are not compatible with base hadoop binaries

### ISSUE THREAD

**Issue by gmatev** [bitnami/bitnami-docker-spark#3]
**Description**

Based on release notes, in `2.4.5-debian-10-r49` additional hadoop-aws and aws-java-sdk jars are added to the base image to facilitate access to AWS using the S3 connector. 

The binaries added appear to be: 
* `aws-java-sdk-bundle-1.11.760.jar`
* `hadoop-aws-3.2.1.jar`

These binaries are incompatible with the `hadoop-common-2.7.3.jar` that are part of the spark 2.4.5 base distribution. 

As a result, it is actually not possible to access files using the S3 connector from a cluster deployed using these base images. 

S3 access is indeed a very common use case, but including binaries in this image which are not part of the baseline Spark distribution can be problematic. Folks already overlay their own binaries on top of this base image assuming that is only contains the standard distribution. Adding additional jars, while useful could result in some version conflicts. 

I have once such case. It is further complicated by the fact that clusters deployed using this base image are accessed from a Jupyter notebook (acting as Spark driver) based on a different image which also needs to have matching spark binaries. We currently do this by installing binaries on the driver image from the base Spark distribution because there is not a good way to get the actual Bitnami managed Spark package used for these images in a way that is predictable for each revision. 

My proposal is that the original change that introduced these binaries be reverted. 

If the additional JARs are kept in the image, they should be the appropriate versions. Based on the hadoop jars already included with spark-2.4.5, these should be `hadoop-aws-2.7.3.jar` and `aws-java-sdk-1.7.4.jar`. 

The alternative is to also upgrade the hadoop binaries distributed with base Spark but that may have other unintended consequences. 

**Steps to reproduce the issue:**

Attempt to load an S3 file using the `S3a` protocol. 

**Describe the results you received:**

Same issue as the one described in https://stackoverflow.com/questions/52310416/noclassdeffounderror-org-apache-hadoop-fs-streamcapabilities-while-reading-s3-d/52562401

**Describe the results you expected:**

File access to work 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

This is demonstratable on images after `2.4.5-debian-10-r49`

**Comment by dani8art** [comment]
Hi @gmatev , thank you for the feedback and a very good explanation. I think you are right if we ship useful packages we need to ensure the compatibility with the currently shipped spark base libraries. We are going to open a task to evaluate the issue and will try to find out a solution. Unfortunately, we couldn't give you an ETA, we will keep you updated.

Thanks!

**Comment by gmatev** [comment]
@dani8art No worries on the ETA. As long as people are aware of it, it is not difficult to work around it. 

One option to consider is actually to offer 2 types of images. One corresponding to the baseline Spark image and a separate one that adds additional packages.

**Comment by dani8art** [comment]
Of course, that could be an option, however, we would like to keep only one image and maybe give the possibility of enabling/disabling this feature by env var or some other mechanism.

**Comment by leqvinh** [comment]
Thank you @gmatev, I'm new to Spark (2.4.5) and I ran into this error "java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found" and I was told to get the correct version of aws-java-sdk and hadoop-aws in order to make it work.  I didn't know which version of each library would work together until I found your post.

**Comment by admssa** [comment]
The bad news is that you can't use AWS EKS IRSA with `aws-java-sdk-1.7.4.jar`. It requires  `1.11.704` at least.

**Comment by andresbono** [comment]
Hi @gmatev, @admssa, @dani8art. We have released a new version of the container that ships compatible jar versions of `aws-java-jdk` and `hadoop-aws`.

- `hadoop-aws-2.7.3.jar`
- `aws-java-sdk-1.7.4.jar`

Please use:

- Container: `2.4.5-debian-10-r136` https://github.com/bitnami/bitnami-docker-spark/commit/1f101933b32c69ccfdddbda84cc53a8e08404a61
- Helm Chart: `1.2.24` https://github.com/bitnami/charts/commit/6c1827c13d6e0ffb72255a1b1e03cd5d6a84070d

In addition, we have opened a PR #6 so that the image can be easily extended to bundle more jars if needed.

**Comment by gmatev** [comment]
@andresbono  This is great. Thank you!

Two related questions: 
(1) Any plans for publishing images that correspond to Spark without Hadoop (e.g https://www.apache.org/dyn/closer.lua/spark/spark-2.4.6/spark-2.4.6-bin-without-hadoop.tgz) So that folks can add later hadoop and aws-hadoop versions as these contain some useful new functionality.
(2) Any plans for Spark3 preview2 image flavor?

**Comment by beltran-rubo** [comment]
Hi @gmatev,

We do not plan to release it without Hadoop binaries for now. We do not usually release "beta" or "preview" versions for components, we will release them once they are stable versions.

**Comment by gmatev** [comment]
@beltran-rubo  thank you!

Looks like this discussion was timely. We have Spark 3.0 GA now  - https://spark.apache.org/releases/spark-release-3-0-0.html

Please consider basing the new images on https://www.apache.org/dyn/closer.lua/spark/spark-3.0.0/spark-3.0.0-bin-hadoop3.2.tgz

Helps bring in access to some of the S3 related improvements others have referenced above. 

Is there a timeline when you expect to release the initial 3.0 based images?

**Comment by beltran-rubo** [comment]
Thanks for letting us know, we noticed it from our version tracker as well. We will work on it, usually it could take 2-3 weeks to have it ready but it really depends on the complexity of the new version.

**Comment by gmatev** [comment]
@beltran-rubo  than you do making the spark3 images available!

Noticed that these images are still based on Hadoop 2.7. I know you guys have been reticent to make multiple versions available, but having an option for folks to get a version with Hadoop 3.2 feel particularly important because of all the important updates in terms of the cloud friendly data comitters. What do you think?

**Comment by beltran-rubo** [comment]
Hi @gmatev, that is a good suggestion, we added it to our to-do list and we will work on creating containers for that particular combination.

**Comment by beltran-rubo** [comment]
Unfortunately this is going to take more time that we expected, we need to work on a way to keep both versions in the repository using the same "branch" version of Hadoop. We need to modify our automation in order to support this.

**Comment by andresbono** [comment]
Hi again @gmatev, we have updated the container image to include Spark with Hadoop `3.2.x`:

- Container: `3.0.0-debian-10-r45` https://github.com/bitnami/bitnami-docker-spark/commit/eda8fdb9524f140e905d79040219ac58ae6e12c0
- Helm Chart: `3.0.0` https://github.com/bitnami/charts/commit/218f9957f1ecf31acc2933cc3a8c00c72cf3f3ef

Hope you find it useful!

**Comment by gmatev** [comment]
This is great. Thank you. 
Might still be worth considering if at some point you want to offer a flavor without hadoop. That said, with the Spark 3 and Hadoop 3.2 combo available, the use cases where customizing hadoop is helpful are probably less impactful.

I think we can close this issue.

**Comment by andresbono** [comment]
Thanks @gmatev. We will check that possibility for future reviews of the container. Thanks for the feedback!
