### ISSUE TITLE
How to use this image to start the thrift-server?

### ISSUE THREAD

**Issue by Ognian** [bitnami/bitnami-docker-spark#32]
Unfortunately all attempts to start the thrift server `start-thriftserver.sh` end with permission problems...
Would be nice if someone at least mentions if it is intended to support this or not...

**Comment by Ognian** [comment]
OMG!!!
Don't know if this is the right way to do it but:
1. login into container as root ad do `chmod g+w /opt/bitnami/spark`
2. login as 1001 ad start with `spark-submit --class org.apache.spark.sql.hive.thriftserver.HiveThriftServer2`

The problem is that the ThriftServer insists to create the megastore_db directory by himself...

**Comment by miguelaeh** [comment]
Hi @Ognian ,
Thank you very much for sharing the solution so other users can solve their problems too!

**Comment by zacMode** [comment]
@miguelaeh - do you have a recommendation of where the `spark-submit` logic could be added to (e.g. a startup script)? 

I'm happy to open a PR to have this be a configurable option, but not sure where the best place for that logic to live.

**Comment by zacMode** [comment]
Actually, i got this  to work by creating my own image, extending bitnami/spark. For posterity, my Dockerfile basically looks like this:

```
FROM bitnami/spark
USER root
# needed so that thrift server can create the megastore_db directory
RUN chmod g+w /opt/bitnami/spark

USER 1001
CMD ["/bin/bash", "-c","/opt/bitnami/spark/bin/spark-submit --class org.apache.spark.sql.hive.thriftserver.HiveThriftServer2"]
```

Thanks @Ognian for actually posting how you solved this, that saved me a ton of time. 

I spent a lot of time trying to figure out how to programatically get this to work, so it might be helpful to mention something in the README for others.

**Comment by miguelaeh** [comment]
Hi @zacMode ,
It would require two main changes:
1. Change the permissions of the directory
2. Change the start command

From my point, those changes are more related to that image than to the Helm Chart. The changes on the permissions for the image are done in the `postunpack.sh`. And the initialization in the `run.sh`.
Then the addition of the new env var for this must be reflected on the Helm Chart, adding a new parameter

**Comment by raefezzeldin** [comment]
hi @zacMode ,

I have created the image as you mentioned above , and I tried to deploy spark using Bitnami Spark Helm Chart. but keeps giving me an error. check the attached logs
[spark-master-0.log](https://github.com/bitnami/bitnami-docker-spark/files/8050107/spark-master-0.log)
.

**Comment by zacMode** [comment]
> hi @zacMode ,
> 
> I have created the image as you mentioned above , and I tried to deploy spark using Bitnami Spark Helm Chart. but keeps giving me an error. check the attached logs [spark-master-0.log](https://github.com/bitnami/bitnami-docker-spark/files/8050107/spark-master-0.log) .

@raefezzeldin Apologies, I'm not going to be able to help much here (i really don't know that much about spark) but looking at your logs it looks like the server _was_ up for ~5 minutes and then was externally killed. Maybe try looking into how ever you're running the container and what might have terminated it? 

```
22/02/11 16:20:33 INFO HiveThriftServer2: HiveThriftServer2 started
22/02/11 16:25:19 ERROR HiveThriftServer2: RECEIVED SIGNAL TERM
```
