### ISSUE TITLE
Python 3.8 or better support

### ISSUE THREAD

**Issue by cosmincatalin** [bitnami/bitnami-docker-spark#34]
Python 3.6 which is the currently supported Python version is fast approaching its end of security support, scheduled for December 2021.
Can you please upgrade the image to make use of Python 3.8 or better?

**Comment by miguelaeh** [comment]
Hi @cosmincatalin ,
Thank you very much for reporting this. We will schedule the change before that date.
Regards.

**Comment by gmatev** [comment]
@miguelaeh does it make sense to consider publishing the image under several different versions of Python? E.g. 3.7, 3.8, 3.9 (or whatever makes sense) so that there is choice for consumers?

**Comment by miguelaeh** [comment]
Hi @gmatev ,
We publish the image versions that are maintained for each application always with the latest versions of the dependencies.
For example, the stable version of Spark is `3`, so we publish Spark version `3` containing always the latest dependencies.
In the case of Python you can see [here](https://github.com/bitnami/bitnami-docker-python) that we support all the maintained versions, and each one will have the latest dependencies.
About releasing the same version of Spark with different versions of the dependencies I think our pipeline is not prepared to do that so it will not be possible by the moment. Nevertheless, you can edit [this line](https://github.com/bitnami/bitnami-docker-spark/blob/b35b292c2f6f70f9cadb0d120adc0209a09d01f7/3/debian-10/Dockerfile#L13) on the Dockerfile and set the Python version of your preference before building the image.
I hope this helps you.

**Comment by miguelaeh** [comment]
Hi @gmatev ,
I am afraid that's not information that is explicit anywhere. Nevertheless, you can use the version you need from [here](https://github.com/bitnami/bitnami-docker-python). You will see a folder per python version. All of them are daily updated so the versions for the packages will also be the latest ones.
If you want to check the packages installed, you will need to exec into the container and check them with something like `pip list`.

**Comment by cosmincatalin** [comment]
Since the issue is obviously not solved, can we have the ticket open until it is?

**Comment by miguelaeh** [comment]
Hi @cosmincatalin ,
I can put the ticket on hold, but this is something that we will schedule before December.

**Comment by andreas-wolf** [comment]
For reference here is a Dockerfile which brute forces a new python version into the container:

```
FROM docker.io/bitnami/spark:3
ARG PYTHON_VERSION
USER root
RUN apt update && \
    apt upgrade -y && \
    apt install -y --no-install-recommends \
    build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libsqlite3-dev libreadline-dev libffi-dev curl libbz2-dev \
    && rm -rf /var/lib/apt/lists/* \
    && curl -O https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tar.xz \
    && tar -xf Python-${PYTHON_VERSION}.tar.xz \
    && cd Python-${PYTHON_VERSION} \
    && ./configure --enable-optimizations \
    && make -j 4 \
    && make altinstall \
    && cd .. \
    && rm -rf Python-${PYTHON_VERSION} \
    && rm Python-${PYTHON_VERSION}.tar.xz \
    && update-alternatives --install /usr/local/bin/python python /usr/local/bin/python${PYTHON_VERSION%.*} 2 \
    && update-alternatives --install /usr/local/bin/python3 python3 /usr/local/bin/python${PYTHON_VERSION%.*} 2 \
    && rm -rf /opt/bitnami/python
USER 1001
```
You can build it with:
`docker build --build-arg PYTHON_VERSION=3.8.11 -t myspark:3_3.8.11 .`

I did not spent too much time on it, could probably be improved. I just needed a specific version to test something.

**Comment by miguelaeh** [comment]
Hi @andreas-wolf ,
It should be easier than that. Just changing on the original Dockerfile [this line](https://github.com/bitnami/bitnami-docker-spark/blob/45062fed5159dc4892dc5b83e9650b2784d2fccb/3/debian-10/Dockerfile#L13) pointing to the desired python version.

**Comment by andreas-wolf** [comment]
Thanks @miguelaeh . I've seen the first comment above about that line. Due to circumstances it was easier to patch the image than to change the CI pipeline and I thought maybe the code would be handy for someone I my situation. Surely changing that line is the recommended way to go.
Btw if you would use ARG for the versions in your Dockerfile one would not need to change the code which would make CI integration a lot easier.

**Comment by miguelaeh** [comment]
Hi @andreas-wolf ,
Thank you for the suggestion. I think we don't use ARG because we set the component's versions that have been run agains our test batteries, so changing them will require the image users to re-test that everything works fine.

**Comment by imranq2** [comment]
Can we just add this line to our Dockerfile that uses your image?
RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "python" "3.6.13-3" --checksum 24afa03a5424804510c07bb5283eca34df2e065140351714298e5f6c3e995ff7

This way we don't need to create our own copy of your Dockerfile and maintain it.

Is there a similar command that will uninstall python 3.6 so we can install python 3.7?

**Comment by miguelaeh** [comment]
Hi @imranq2 ,
> Is there a similar command that will uninstall python 3.6 so we can install python 3.7?

There isn't a command to uninstall it, but you can remove the `/opt/bitnami/python` directory and then install `3.7`.

> Can we just add this line to our Dockerfile that uses your image?

I guess you are talking about use `FROM` our image and replace the python version right? I think you can do that without problems.

**Comment by george-zubrienko** [comment]
Just to confirm what @miguelaeh wrote, we are using custom image based on bitnami and replacing python version like this:
```
FROM bitnami/spark:3.1.2

...

USER 0

# Update python version to 3.9 until Bitnami releases their own update
RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "python" "3.9.6-0"
...
```
Then from inside the container:
```
I have no name!@f980ea3979bd:/opt/bitnami/spark$ python3
Python 3.9.6 (default, Jun 28 2021, 21:24:30)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

Really nice image btw :)

**Comment by miguelaeh** [comment]
Thank you very much @george-zubrienko for adding the example!

**Comment by brsolomon-deloitte** [comment]
Another reason for creating public-facing / publicly-documented ways to select and manipulate the Python version on the Spark workers is that clients in `deployMode=client` must match in Python minor version. Otherwise, you get:

> RuntimeError: Python in worker has different version 3.6 than that in driver 3.9, PySpark cannot run with different minor versions. Please check environment variables PYSPARK_PYTHON and PYSPARK_DRIVER_PYTHON are correctly set.

**Comment by brsolomon-deloitte** [comment]
For anyone else looking for a MVCE, putting together some different parts of this thread:

```docker
FROM bitnami/spark:3.2.0-debian-10-r29
ARG PYTHON_VERSION="3.9.9-0"
ARG PYTHON_SHA256SUM="592655ff2f275a22358bc44b02d5d3a2c18af7427990ca92319c5a9154b700f7"
USER root
# https://bitnami .com/stack/python/containers
RUN set -eux \
    && . /opt/bitnami/scripts/libcomponent.sh \
    && component_unpack "python" "$PYTHON_VERSION" --checksum "$PYTHON_SHA256SUM"
USER 1001
```

**Comment by miguelaeh** [comment]
Hi guys, thanks for the patience, the latest image is using Python `3.8`:
```
I have no name!@d2c7907ae16a:/opt/bitnami/spark$ python --version
Python 3.8.12
```
