### ISSUE TITLE
Add support for Spark Submit Kubernetes Master

### ISSUE THREAD

**Issue by porteken** [bitnami/bitnami-docker-spark#38]
Is it possible to add support for Spark Submit Kubernetes Master https://spark.apache.org/docs/latest/running-on-kubernetes.html?

**Comment by rafariossaa** [comment]
Hi,
  Thanks for suggesting this.
  It should be possible to add support to this, I am creating an internal task to study this.
  I could not provide an ETA for this or if it would be added to our catalog in a future.
  We will come back as soon as we have news.

**Comment by warichet** [comment]
Hello,
i have modified the entrypoint.sh to deal with driver argument.
That's ugly but it seems work.

Best regards
Sébastien

#!/bin/bash

# echo commands to the terminal output
set -ex
set -o errexit
set -o nounset
set -o pipefail

# Load libraries
. /opt/bitnami/scripts/libbitnami.sh
. /opt/bitnami/scripts/libspark.sh

# Load Spark environment variables
eval "$(spark_env)"

print_welcome_page

if [ ! $EUID -eq 0 ] && [ -e "$LIBNSS_WRAPPER_PATH" ]; then
    echo "spark:x:$(id -u):$(id -g):Spark:$SPARK_HOME:/bin/false" > "$NSS_WRAPPER_PASSWD"
    echo "spark:x:$(id -g):" > "$NSS_WRAPPER_GROUP"
    echo "LD_PRELOAD=$LIBNSS_WRAPPER_PATH" >> "$SPARK_CONFDIR/spark-env.sh"
fi

if [[ "$*" = "/opt/bitnami/scripts/spark/run.sh" ]]; then
    info "** Starting Spark setup **"
    /opt/bitnami/scripts/spark/setup.sh
    info "** Spark setup finished! **"
fi

case "$1" in
  driver)
    shift 1
    CMD=(
      "$SPARK_HOME/bin/spark-submit"
      --conf "spark.driver.bindAddress=$SPARK_DRIVER_BIND_ADDRESS"
      --deploy-mode client
      "$@"
    )
    ;;
  *)
    echo "Non-spark-on-k8s command provided, proceeding in pass-through mode..."
    CMD=("$@")
    ;;
esac

echo ""
exec "${CMD[@]}"

**Comment by rafariossaa** [comment]
Hi,
  Maybe you want to send a PR so we can review it properly and merge it.
  Would you send it?

**Comment by warichet** [comment]
Hi
i am not an expert in github, but i will try to send it.
Best regards
Seb

**Comment by rafariossaa** [comment]
Thanks !. 
We will be glad to review and merge it.

**Comment by rrcic** [comment]
> 

It seems that the same error will still be reported after modification
### 
++ SPARK_NO_DAEMONIZE=true
++ export SPARK_RPC_AUTHENTICATION_ENABLED=no
++ SPARK_RPC_AUTHENTICATION_ENABLED=no
++ export SPARK_RPC_AUTHENTICATION_SECRET=
++ SPARK_RPC_AUTHENTICATION_SECRET=
++ export SPARK_RPC_ENCRYPTION_ENABLED=no
++ SPARK_RPC_ENCRYPTION_ENABLED=no
++ export SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
++ SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
++ export SPARK_SSL_ENABLED=no
++ SPARK_SSL_ENABLED=no
++ export SPARK_SSL_KEY_PASSWORD=
++ SPARK_SSL_KEY_PASSWORD=
++ export SPARK_SSL_KEYSTORE_PASSWORD=
++ SPARK_SSL_KEYSTORE_PASSWORD=
++ export SPARK_SSL_KEYSTORE_FILE=/opt/bitnami/spark/conf/certs/spark-keystore.jks
++ SPARK_SSL_KEYSTORE_FILE=/opt/bitnami/spark/conf/certs/spark-keystore.jks
++ export SPARK_SSL_TRUSTSTORE_PASSWORD=
++ SPARK_SSL_TRUSTSTORE_PASSWORD=
++ export SPARK_SSL_TRUSTSTORE_FILE=/opt/bitnami/spark/conf/certs/spark-truststore.jks
++ SPARK_SSL_TRUSTSTORE_FILE=/opt/bitnami/spark/conf/certs/spark-truststore.jks
++ export SPARK_SSL_NEED_CLIENT_AUTH=yes
++ SPARK_SSL_NEED_CLIENT_AUTH=yes
++ export SPARK_SSL_PROTOCOL=TLSv1.2
++ SPARK_SSL_PROTOCOL=TLSv1.2
++ export SPARK_WEBUI_SSL_PORT=
++ SPARK_WEBUI_SSL_PORT=
++ export SPARK_METRICS_ENABLED=false
++ SPARK_METRICS_ENABLED=false
++ export SPARK_DAEMON_USER=spark
++ SPARK_DAEMON_USER=spark
++ export SPARK_DAEMON_GROUP=spark
++ SPARK_DAEMON_GROUP=spark
+ print_welcome_page
+ [[ -z '' ]]
+ [[ -n spark ]]
+ print_image_welcome_page
+ local github_url=https://github.com/bitnami/bitnami-docker-spark
+ log ''
++ date '+%T.%2N '
+ stderr_print '\033[38;5;6m \033[38;5;5m05:44:45.61 \033[0m'
+ local bool=false
+ shopt -s nocasematch
+ [[ false = 1 ]]
+ [[ false =~ ^(yes|true)$ ]]
+ printf '%b\n' '\033[38;5;6m \033[38;5;5m05:44:45.61 \033[0m'
[38;5;6m [38;5;5m05:44:45.61 [0m
+ log '\033[1mWelcome to the Bitnami spark container\033[0m'
++ date '+%T.%2N '
+ stderr_print '\033[38;5;6m \033[38;5;5m05:44:45.61 \033[0m\033[1mWelcome to the Bitnami spark container\033[0m'
+ local bool=false
+ shopt -s nocasematch
+ [[ false = 1 ]]
+ [[ false =~ ^(yes|true)$ ]]
+ printf '%b\n' '\033[38;5;6m \033[38;5;5m05:44:45.61 \033[0m\033[1mWelcome to the Bitnami spark container\033[0m'
[38;5;6m [38;5;5m05:44:45.61 [0m[1mWelcome to the Bitnami spark container[0m
+ log 'Subscribe to project updates by watching \033[1mhttps://github.com/bitnami/bitnami-docker-spark\033[0m'
++ date '+%T.%2N '
+ stderr_print '\033[38;5;6m \033[38;5;5m05:44:45.61 \033[0mSubscribe to project updates by watching \033[1mhttps://github.com/bitnami/bitnami-docker-spark\033[0m'
+ local bool=false
+ shopt -s nocasematch
+ [[ false = 1 ]]
+ [[ false =~ ^(yes|true)$ ]]
+ printf '%b\n' '\033[38;5;6m \033[38;5;5m05:44:45.61 \033[0mSubscribe to project updates by watching \033[1mhttps://github.com/bitnami/bitnami-docker-spark\033[0m'
[38;5;6m [38;5;5m05:44:45.61 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-spark[0m
+ log 'Submit issues and feature requests at \033[1mhttps://github.com/bitnami/bitnami-docker-spark/issues\033[0m'
++ date '+%T.%2N '
+ stderr_print '\033[38;5;6m \033[38;5;5m05:44:45.61 \033[0mSubmit issues and feature requests at \033[1mhttps://github.com/bitnami/bitnami-docker-spark/issues\033[0m'
+ local bool=false
+ shopt -s nocasematch
+ [[ false = 1 ]]
+ [[ false =~ ^(yes|true)$ ]]
+ printf '%b\n' '\033[38;5;6m \033[38;5;5m05:44:45.61 \033[0mSubmit issues and feature requests at \033[1mhttps://github.com/bitnami/bitnami-docker-spark/issues\033[0m'
[38;5;6m [38;5;5m05:44:45.61 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-spark/issues[0m
+ log ''
++ date '+%T.%2N '
+ stderr_print '\033[38;5;6m \033[38;5;5m05:44:45.61 \033[0m'
+ local bool=false
+ shopt -s nocasematch
+ [[ false = 1 ]]
+ [[ false =~ ^(yes|true)$ ]]
+ printf '%b\n' '\033[38;5;6m \033[38;5;5m05:44:45.61 \033[0m'
[38;5;6m [38;5;5m05:44:45.61 [0m
+ '[' '!' 1001 -eq 0 ']'
+ '[' -e /opt/bitnami/common/lib/libnss_wrapper.so ']'
++ id -u
++ id -g
+ echo spark:x:1001:0:Spark:/opt/bitnami/spark:/bin/false
++ id -g
+ echo spark:x:0:
+ echo LD_PRELOAD=/opt/bitnami/common/lib/libnss_wrapper.so
+ [[ driver-py --properties-file /opt/spark/conf/spark.properties --class org.apache.spark.deploy.PythonRunner = \/\o\p\t\/\b\i\t\n\a\m\i\/\s\c\r\i\p\t\s\/\s\p\a\r\k\/\r\u\n\.\s\h ]]
+ case "$1" in
+ echo 'Non-spark-on-k8s command provided, proceeding in pass-through mode...'
+ CMD=("$@")
Non-spark-on-k8s command provided, proceeding in pass-through mode...

+ echo ''
+ exec driver-py --properties-file /opt/spark/conf/spark.properties --class org.apache.spark.deploy.PythonRunner
/opt/bitnami/scripts/spark/entrypoint.sh: line 47: exec: driver-py: not found

**Comment by rrcic** [comment]
@warichet It seems that an error will still be reported after modification
'''shell
Non-spark-on-k8s command provided, proceeding in pass-through mode...

+ echo ''
+ exec driver-py --properties-file /opt/spark/conf/spark.properties --class org.apache.spark.deploy.PythonRunner
/opt/bitnami/scripts/spark/entrypoint.sh: line 47: exec: driver-py: not found

**Comment by rrcic** [comment]
@warichet It seems that an error will still be reported after modification
`++ SPARK_NO_DAEMONIZE=true
++ export SPARK_RPC_AUTHENTICATION_ENABLED=no
++ SPARK_RPC_AUTHENTICATION_ENABLED=no
++ export SPARK_RPC_AUTHENTICATION_SECRET=
++ SPARK_RPC_AUTHENTICATION_SECRET=
++ export SPARK_RPC_ENCRYPTION_ENABLED=no
++ SPARK_RPC_ENCRYPTION_ENABLED=no
++ export SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
++ SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
++ export SPARK_SSL_ENABLED=no
++ SPARK_SSL_ENABLED=no
++ export SPARK_SSL_KEY_PASSWORD=
++ SPARK_SSL_KEY_PASSWORD=
++ export SPARK_SSL_KEYSTORE_PASSWORD=
++ SPARK_SSL_KEYSTORE_PASSWORD=
++ export SPARK_SSL_KEYSTORE_FILE=/opt/bitnami/spark/conf/certs/spark-keystore.jks
++ SPARK_SSL_KEYSTORE_FILE=/opt/bitnami/spark/conf/certs/spark-keystore.jks
++ export SPARK_SSL_TRUSTSTORE_PASSWORD=
++ SPARK_SSL_TRUSTSTORE_PASSWORD=
++ export SPARK_SSL_TRUSTSTORE_FILE=/opt/bitnami/spark/conf/certs/spark-truststore.jks
++ SPARK_SSL_TRUSTSTORE_FILE=/opt/bitnami/spark/conf/certs/spark-truststore.jks
++ export SPARK_SSL_NEED_CLIENT_AUTH=yes
++ SPARK_SSL_NEED_CLIENT_AUTH=yes
++ export SPARK_SSL_PROTOCOL=TLSv1.2
++ SPARK_SSL_PROTOCOL=TLSv1.2
++ export SPARK_WEBUI_SSL_PORT=
++ SPARK_WEBUI_SSL_PORT=
++ export SPARK_METRICS_ENABLED=false
++ SPARK_METRICS_ENABLED=false
++ export SPARK_DAEMON_USER=spark
++ SPARK_DAEMON_USER=spark
++ export SPARK_DAEMON_GROUP=spark
++ SPARK_DAEMON_GROUP=spark
+ print_welcome_page
+ [[ -z '' ]]
+ [[ -n spark ]]
+ print_image_welcome_page
+ local github_url=https://github.com/bitnami/bitnami-docker-spark
+ log ''
++ date '+%T.%2N '
+ stderr_print '\033[38;5;6m \033[38;5;5m05:44:45.61 \033[0m'
+ local bool=false
+ shopt -s nocasematch
+ [[ false = 1 ]]
+ [[ false =~ ^(yes|true)$ ]]
+ printf '%b\n' '\033[38;5;6m \033[38;5;5m05:44:45.61 \033[0m'
[38;5;6m [38;5;5m05:44:45.61 [0m
+ log '\033[1mWelcome to the Bitnami spark container\033[0m'
++ date '+%T.%2N '
+ stderr_print '\033[38;5;6m \033[38;5;5m05:44:45.61 \033[0m\033[1mWelcome to the Bitnami spark container\033[0m'
+ local bool=false
+ shopt -s nocasematch
+ [[ false = 1 ]]
+ [[ false =~ ^(yes|true)$ ]]
+ printf '%b\n' '\033[38;5;6m \033[38;5;5m05:44:45.61 \033[0m\033[1mWelcome to the Bitnami spark container\033[0m'
[38;5;6m [38;5;5m05:44:45.61 [0m[1mWelcome to the Bitnami spark container[0m
+ log 'Subscribe to project updates by watching \033[1mhttps://github.com/bitnami/bitnami-docker-spark\033[0m'
++ date '+%T.%2N '
+ stderr_print '\033[38;5;6m \033[38;5;5m05:44:45.61 \033[0mSubscribe to project updates by watching \033[1mhttps://github.com/bitnami/bitnami-docker-spark\033[0m'
+ local bool=false
+ shopt -s nocasematch
+ [[ false = 1 ]]
+ [[ false =~ ^(yes|true)$ ]]
+ printf '%b\n' '\033[38;5;6m \033[38;5;5m05:44:45.61 \033[0mSubscribe to project updates by watching \033[1mhttps://github.com/bitnami/bitnami-docker-spark\033[0m'
[38;5;6m [38;5;5m05:44:45.61 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-spark[0m
+ log 'Submit issues and feature requests at \033[1mhttps://github.com/bitnami/bitnami-docker-spark/issues\033[0m'
++ date '+%T.%2N '
+ stderr_print '\033[38;5;6m \033[38;5;5m05:44:45.61 \033[0mSubmit issues and feature requests at \033[1mhttps://github.com/bitnami/bitnami-docker-spark/issues\033[0m'
+ local bool=false
+ shopt -s nocasematch
+ [[ false = 1 ]]
+ [[ false =~ ^(yes|true)$ ]]
+ printf '%b\n' '\033[38;5;6m \033[38;5;5m05:44:45.61 \033[0mSubmit issues and feature requests at \033[1mhttps://github.com/bitnami/bitnami-docker-spark/issues\033[0m'
[38;5;6m [38;5;5m05:44:45.61 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-spark/issues[0m
+ log ''
++ date '+%T.%2N '
+ stderr_print '\033[38;5;6m \033[38;5;5m05:44:45.61 \033[0m'
+ local bool=false
+ shopt -s nocasematch
+ [[ false = 1 ]]
+ [[ false =~ ^(yes|true)$ ]]
+ printf '%b\n' '\033[38;5;6m \033[38;5;5m05:44:45.61 \033[0m'
[38;5;6m [38;5;5m05:44:45.61 [0m
+ '[' '!' 1001 -eq 0 ']'
+ '[' -e /opt/bitnami/common/lib/libnss_wrapper.so ']'
++ id -u
++ id -g
+ echo spark:x:1001:0:Spark:/opt/bitnami/spark:/bin/false
++ id -g
+ echo spark:x:0:
+ echo LD_PRELOAD=/opt/bitnami/common/lib/libnss_wrapper.so
+ [[ driver-py --properties-file /opt/spark/conf/spark.properties --class org.apache.spark.deploy.PythonRunner = \/\o\p\t\/\b\i\t\n\a\m\i\/\s\c\r\i\p\t\s\/\s\p\a\r\k\/\r\u\n\.\s\h ]]
+ case "$1" in
+ echo 'Non-spark-on-k8s command provided, proceeding in pass-through mode...'
+ CMD=("$@")
Non-spark-on-k8s command provided, proceeding in pass-through mode...

+ echo ''
+ exec driver-py --properties-file /opt/spark/conf/spark.properties --class org.apache.spark.deploy.PythonRunner
/opt/bitnami/scripts/spark/entrypoint.sh: line 47: exec: driver-py: not found`

**Comment by rrcic** [comment]
Hello @warichet 
I modified entrypoint.sh according to your suggestion, but I still have the same error.

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
