### ISSUE TITLE
Readme incorrect on Setting up a Spark Cluster

### ISSUE THREAD

**Issue by gbeaven90** [bitnami/bitnami-docker-spark#53]
The **Setting up a Spark Cluster** section of the README.md file is incorrect:

> By default, when you deploy the docker-compose file you will get a Spark cluster with 1 master and 1 worker.

This is not true. By default deploying the docker-compose file with `docker compose up` starts a Spark cluster with 1 master and 2 workers:
![image](https://user-images.githubusercontent.com/22197442/141373780-611f1cee-53a9-45ad-9d35-ba5c841fb4fa.png)

> If you want N workers, all you need to do is start the docker-compose deployment with the following command:
> $ docker-compose up --scale spark-worker=3

This is also not true. Deploying the docker-compose file with `docker-compose up --scale spark-worker=3` produces the same results from above (1 master and 2 workers). Same with `docker-compose up --scale spark-worker=10` etc.

**Comment by alemorcuq** [comment]
You are right. Thanks for creating a PR addressing it.

**Comment by javsalgar** [comment]
Closing it as the PR was merged.
