### ISSUE TITLE
/opt/bitnami/scripts/spark/entrypoint.sh: line 32: exec: driver: not found

### ISSUE THREAD

**Issue by aaronhadoop** [bitnami/bitnami-docker-spark#56]
Refer to spark's official website(https://spark.apache.org/docs/3.2.0/running-on-kubernetes.html), and the image of bitnami/spark(https://hub.docker.com/r/bitnami/spark), 
I want to submit spark task to kubernetes with below command:
```
cd /root/spark-3.2.0-bin-hadoop2.7/bin/
./spark-submit \
    --master k8s://https://KUBERNETES_API_IP:6443 \
    --deploy-mode cluster \
    --name spark-pi \
    --class org.apache.spark.examples.SparkPi \
    --conf spark.executor.instances=5 \
    --conf spark.kubernetes.container.image=bitnami/spark:latest \
    local:///opt/spark/examples/jars/*.jar
```

but  run failed with below result:
```
[root@k8s-master1 bin]# kubectl logs spark-pi-eafb267d5f9815ee-driver
 04:12:26.14 
 04:12:26.15 Welcome to the Bitnami spark container
 04:12:26.15 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-spark
 04:12:26.16 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-spark/issues
 04:12:26.16 

/opt/bitnami/scripts/spark/entrypoint.sh: line 32: exec: driver: not found
```

**Version**

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
```

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.10
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        b485636
 Built:             Mon Oct 25 07:44:50 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.10
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       e2f740d
  Built:            Mon Oct 25 07:43:13 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)
  scan: Docker Scan (Docker Inc., v0.9.0)

Server:
 Containers: 68
  Running: 18
  Paused: 0
  Stopped: 50
 Images: 18
 Server Version: 20.10.10
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.127-1.el7.elrepo.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 23.49GiB
 Name: k8s-master1
 ID: XJXN:XGPE:7V4P:ITI4:XNP2:HEI3:7VPP:DLDW:MCVG:UICR:SVZN:OJ42
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://7bezldxe.mirror.aliyuncs.com/
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by aaronhadoop** [comment]
maybe this image does not suppprt run on kubernetes.I recorded it in this document (https://yujianxin.blog.csdn.net/article/details/121586848)

**Comment by aaronhadoop** [comment]
maybe this image does not suppprt run on kubernetes.I recorded it in this document (https://yujianxin.blog.csdn.net/article/details/121586848)

**Comment by miguelaeh** [comment]
Hi @aaronhadoop ,
This image runs on Kubernetes, we even have a Spark Helm Chart at: https://github.com/bitnami/charts/tree/master/bitnami/spark

There, you can see how to submit an application: https://github.com/bitnami/charts/tree/master/bitnami/spark#submit-an-application

**Comment by phuongnd96** [comment]
Sorry but this seems broken. I'm using helm chart with image version 3.2.0-debian-10-r33.

` spark-submit \
    --class org.apache.spark.examples.SparkPi \
    --conf spark.kubernetes.container.image=docker.io/bitnami/spark:3 \
    --master k8s://https://<k8s_url>\
    --deploy-mode cluster \
    local:///tmp/spark-examples_2.12-3.2.0.jar 1000`

Spawned driver pod show the following logs:

`/opt/bitnami/scripts/spark/entrypoint.sh: line 32: exec: driver: not found`

**Comment by javsalgar** [comment]
Could you provide more details on that driver pod? Could you show the default command it should run?

**Comment by xwoodpecker** [comment]
Same problem here. Running on minikube:

The spark submit command:
`./bin/spark-submit` 
--class org.apache.spark.examples.SparkPi 
--conf spark.kubernetes.container.image=bitnami/spark:3 
--master k8s://https://192.168.178.53:8443 
--deploy-mode cluster 
--conf spark.kubernetes.file.upload.path=”/opt/spark/app/jars” 
./examples/jars/spark-examples_2.12-3.2.0.jar 1000`

Result:
`21/12/11 17:39:29 INFO LoggingPodStatusWatcherImpl: Container final statuses:
         container name: spark-kubernetes-driver
         container image: bitnami/spark:3
         container state: terminated
         container started at: 2021-12-11T16:39:29Z
         container finished at: 2021-12-11T16:39:30Z
         exit code: 127
         termination reason: Error
21/12/11 17:39:29 INFO LoggingPodStatusWatcherImpl: Application org.apache.spark.examples.SparkPi with submission ID default:org-apache-spark-examples-sparkpi-aae1e87daa5d15bb-driver finished` 

Pod Logs:
`PS C:\spark-3.2.0-bin-hadoop3.2> kubectl logs org-apache-spark-examples-sparkpi-aae1e87daa5d15bb-driver
 16:39:30.01
 16:39:30.01 Welcome to the Bitnami spark container
 16:39:30.01 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-spark
 16:39:30.01 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-spark/issues
 16:39:30.01

/opt/bitnami/scripts/spark/entrypoint.sh: line 32: exec: driver: not found`

**Comment by ShibraAmin18** [comment]
Hi @aaronhadoop, Can you please update me on this error, what conclusion you came to or any recommended solution ?
My logs shows the same error:

`/opt/bitnami/scripts/spark/entrypoint.sh: line 32: exec: driver: not found`

**Comment by rrcic** [comment]
I have encountered the same problem. The driver pod cannot start normally and displays "driver not found". I don't know how to solve this problem. I'm very confused.

**Comment by javsalgar** [comment]
Hi,

Could you provide more details about the platform and the exact commands to reproduce?

**Comment by rrcic** [comment]
`/opt/bitnami/scripts/spark/entrypoint.sh: line 32: exec: driver: not found`

**Comment by rrcic** [comment]
I try to submit a SparkApplication using the command`kubectl create -f test.yaml`. The version of k8s cluster is 1.20.11-aliyun.1(I build the k8s cluster using the service of aliyun).
The following is part of the test.yaml.
`apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: wordcount-test
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  sparkVersion: "3.2.1"
  mode: cluster
  image: "bitnami/spark:3"
  imagePullPolicy: Always`
When I try to use the command`kubectl create -f test.yaml`,the driver pod can't run normally.
My logs shows the following error.
`/opt/bitnami/scripts/spark/entrypoint.sh: line 32: exec: driver: not found`

**Comment by miguelaeh** [comment]
I investigated the issue and was able to reproduce it.
What is happening is that when submitting the Spark Pi example, spark is creating a Pod with the image `bitnami/spark:3` that executes the following command:
```
      driver
      --properties-file
      /opt/spark/conf/spark.properties
      --class
      org.apache.spark.examples.SparkPi
      spark-internal
      1000
```

And into the `bitnami/spark:3` there is not a `driver` command.
So, there are two options:
1. Change the option `--conf spark.kubernetes.container.image=<spark-image>` in the `spark-submit` command to use an image that has the `driver` command.
2. Add that command to our image. For this case, I would like to understand from someone more experienced in Spark if the `driver` command is something used always, or it is just useful in some concrete examples like SparkPi

**Comment by rrcic** [comment]
In my opinion, the `driver` command is something used always. When I try to submmit a spark work to k8s, the driver pod is supposed to run first. 
So, the image `bitnami/spark` can't be used in k8s unless you add that command to it. In that case, I will build a spark image by myself. However, I sincerely hope that you can add the `driver` command to the image`bitnami/spark`.
Thanks a lot.

**Comment by javsalgar** [comment]
Hi,

Thanks for letting us know, then, if it is something common, we should work on adding the driver command to the image.

**Comment by gongomgra** [comment]
Hi,

We have just added the `driver` command to our latest image (`3.2.1-debian-10-r71`) and we also updated the [README.md file of the chart](https://github.com/bitnami/charts/tree/master/bitnami/spark#submit-an-application) to properly configure the `SPARK_MASTER_URL` into the driver pod so it can effectively connect with the cluster. Let us know if it works for you

**Comment by ebuildy** [comment]
``executor`` is still missing (got error: ``/opt/bitnami/scripts/spark/entrypoint.sh: line 51: exec: executor: not found``)

**Comment by gongomgra** [comment]
Thanks for your message, @ebuildy. I will open a task for the team to add the `executor` command as well. Can you share an example with us to reproduce the error?

**Comment by gongomgra** [comment]
@ebuildy thanks for sharing the `executor` definition. However, could you still share with us a scenario in which we can reproduce your error in order to verify the implemented solution?
