### ISSUE TITLE
Spark-submit job write permission denied deploy-mode cluster

### ISSUE THREAD

**Issue by willim32533** [bitnami/bitnami-docker-spark#57]
Not sure if this is a bug, or if I am doing something incorrectly to prevent spark-submit deploy-mode=cluster from being able to write tables to a mapped volume (persistent storage).  The dockerfiles and docker compose files are attached along with the spark log files from the failed jobs and the successful job.

Error received:

```
java.io.FileNotFoundException: /usr/bin/spark/hadoop/departuredelays.csv.Delta/part-00000-e04f7d04-4cab-4c67-80d6-0c38ca657354-c000.snappy.parquet (Permission denied)
```
**Description**
Submitting the spark job like this works:
```
./bin/spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner \
   --conf "spark.eventLog.enabled=true" \
   --conf "spark.eventLog.dir=file:/usr/bin/spark/hadoop/logs" \
   --master spark://spark:7077 \
   /opt/bitnami/spark/jars/microsoft-spark-3-1_2.12-2.0.0.jar \
   dotnet /usr/bin/spark/hadoop/app/SparkNet.dll "/usr/bin/spark/hadoop" "newdeltafilename.test"
```

However, when changing either the spark-submit configuration to specify cluster mode:
```
./bin/spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner \
   --conf "spark.eventLog.enabled=true" \
   --conf "spark.eventLog.dir=file:/usr/bin/spark/hadoop/logs" \
   --master spark://spark:7077 \
   --deploy-mode cluster \
   /opt/bitnami/spark/jars/microsoft-spark-3-1_2.12-2.0.0.jar \
   dotnet /usr/bin/spark/hadoop/app/SparkNet.dll "/usr/bin/spark/hadoop" "newdeltafilename.test"
```

or, using the following in the sample .NET app's SparkSession object generates an error: (complete log files for the successful job and the job that fails are available, if needed)
```
SparkSession spark = SparkSession
                .Builder()
                .Master("spark://spark:7077")
                .AppName("SparkNet")
                .GetOrCreate();
```
[workerlog-failed-app-20211117154356-0002.txt](https://github.com/bitnami/bitnami-docker-spark/files/7621643/workerlog-failed-app-20211117154356-0002.txt)
[workerlog-failed-app-20211117164918-0003.txt](https://github.com/bitnami/bitnami-docker-spark/files/7621644/workerlog-failed-app-20211117164918-0003.txt)
[master-success-local-1637168268123.txt](https://github.com/bitnami/bitnami-docker-spark/files/7621671/master-success-local-1637168268123.txt)
[build-spark-base-image.Dockerfile.txt](https://github.com/bitnami/bitnami-docker-spark/files/7621684/build-spark-base-image.Dockerfile.txt)
[build-spark-worker-image.Dockerfile.txt](https://github.com/bitnami/bitnami-docker-spark/files/7621685/build-spark-worker-image.Dockerfile.txt)
[build-spark-master-image.Dockerfile.txt](https://github.com/bitnami/bitnami-docker-spark/files/7621686/build-spark-master-image.Dockerfile.txt)
[docker-compose.yml.txt](https://github.com/bitnami/bitnami-docker-spark/files/7621689/docker-compose.yml.txt)

**Comment by carrodher** [comment]
Can you share with us the `docker-compose.yaml` or the method/command you are using to deploy the application?
Please, take into account this container is [non-root container](https://github.com/bitnami/bitnami-docker-spark#why-use-a-non-root-container) so you should set the proper permissions to the volume so the container is able to write it.

**Comment by willim32533** [comment]
docker-compose:
version: '3.8'

services:
  spark:
    image: dotnetcore31-spark312-master:3.1.2
    user: root
    ports:
      - '4040:4040'
      - '8080:8080'
    volumes:
      - C:\sparklocalfiles:/usr/bin/spark/hadoop
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

  spark-worker-1:
    image: dotnetcore31-spark312-worker:3.1.2
    user: root
    ports:
      - '4041:8081'
    depends_on: 
      - spark
    volumes:
      - C:\sparklocalfiles:/usr/bin/spark/hadoop
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    
  spark-worker-2:
    image: dotnetcore31-spark312-worker:3.1.2
    user: root
    ports:
      - '4042:8081'
    depends_on: 
      - spark
    volumes:
      - C:\sparklocalfiles:/usr/bin/spark/hadoop
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    

./bin/spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner \
   --conf "spark.eventLog.enabled=true" \
   --conf "spark.eventLog.dir=file:/usr/bin/spark/hadoop/logs" \
   --master spark://spark:7077 \
   --deploy-mode cluster \   # adding deploy-mode cluster causes the failure
   /opt/bitnami/spark/jars/microsoft-spark-3-1_2.12-2.0.0.jar \
   dotnet /usr/bin/spark/hadoop/app/SparkNet.dll "/usr/bin/spark/hadoop" "newdeltafilename.test"

**Comment by willim32533** [comment]
both the master and the worker containers are running as root

**Comment by willim32533** [comment]
#docker-compose.yml
version: '3.8'

services:
  spark:
    image: dotnetcore31-spark312-master:3.1.2
    user: root
    ports:
      - '4040:4040'
      - '8080:8080'
    volumes:
      - C:\sparklocalfiles:/usr/bin/spark/hadoop
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

  spark-worker-1:
    image: dotnetcore31-spark312-worker:3.1.2
    user: root
    ports:
      - '4041:8081'
    depends_on: 
      - spark
    volumes:
      - C:\sparklocalfiles:/usr/bin/spark/hadoop
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    
  spark-worker-2:
    image: dotnetcore31-spark312-worker:3.1.2
    user: root
    ports:
      - '4042:8081'
    depends_on: 
      - spark
    volumes:
      - C:\sparklocalfiles:/usr/bin/spark/hadoop
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

**Comment by carrodher** [comment]
Did you perform any change to the `dotnetcore31-spark312-master:3.1.2` image or is just the bitnami one renamed and pushed to another repo?
Apart from that, the permissions of the local volume (the directory in the host) match with the ones used inside the container?

**Comment by willim32533** [comment]
My apologies.  The image dotnetcore31-spark312-master:3.1.2 is created by the dockerfile: 
[build-spark-base-image.Dockerfile.txt](https://github.com/bitnami/bitnami-docker-spark/files/7621684/build-spark-base-image.Dockerfile.txt)
and then applying this dockerfile
[build-spark-master-image.Dockerfile.txt](https://github.com/bitnami/bitnami-docker-spark/files/7621686/build-spark-master-image.Dockerfile.txt)

**Comment by migruiz4** [comment]
Hi @willim32533,

We may not be able to provide further help given the level of customization of your image since we can not ensure it is an issue with the base image or caused by the changes introduced in your Dockerfile.

But, considering the error:
> java.io.FileNotFoundException: /usr/bin/spark/hadoop/departuredelays.csv.Delta/part-00000-e04f7d04-4cab-4c67-80d6-0c38ca657354-c000.snappy.parquet (Permission denied)

And that `/usr/bin/spark/hadoop/` is a mounted volume, I would say that the problem is not the image itself but the permissions in your host.
>     volumes:
>      - C:\sparklocalfiles:/usr/bin/spark/hadoop

I would suggest it could be an issue with Docker for Windows (see https://stackoverflow.com/questions/43880764/in-docker-for-windows-permissions-denied-for-mkdir-chown). These issues are also frequent when using shared volumes e.g. NFS.
That is because, although you run the container as `root`, in those cases your container may not have full permission over the volume.

**Comment by willim32533** [comment]
@migruiz4 Thank you for your reply.  What does not make sense to me is that if it were a problem with permissions, or Docker, then why does everything run successfully when the spark-submit is executed like this, without specifying --deploy-mode cluster?

This way works:
`./bin/spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner \`
`   --conf "spark.eventLog.enabled=true" \`
`   --conf "spark.eventLog.dir=file:/usr/bin/spark/hadoop/logs" \`
`   --master spark://spark:7077 \`
`   /opt/bitnami/spark/jars/microsoft-spark-3-1_2.12-2.0.0.jar \`
`   dotnet /usr/bin/spark/hadoop/app/SparkNet.dll "/usr/bin/spark/hadoop" "newdeltafilename.test"`

**Comment by javsalgar** [comment]
I'm not sure I understand the paths you are using here

`/usr/bin/spark/hadoop/`

Shouldn't these be the ones under `/opt/bitnami/spark`?

**Comment by psabhay** [comment]
I am also struggling with the same issue. What I have seen is the the containers run as `spark` even if you use `user: root`. I believe this could be the main bug that the containers are always running as `spark` user. Can anyone confirm if this is the case?

**Comment by rafariossaa** [comment]
Could you try a simpler case without all that customization ?, I agree with @migruiz4, I think this is an issue issue with docker and windows. 
Could you try in a linux machine ?

**Comment by willim32533** [comment]
I will try to build and test a new simple set-up; however, my environment is using Linux docker images on a Windows host.

**Comment by willim32533** [comment]
@rafariossaa Trying to come up with a sample without any customization and running into an issue since stand alone clusters don't support python apps using cluster deploy mode and I don't know java or scala (I am primarily a .NET developer).

**Comment by rafariossaa** [comment]
Hi,
  Thanks @willim32533, it would be easier just to start checking it in a linux machine. Maybe, you can try that first in a VM inside your windows host.

**Comment by willim32533** [comment]
Hi @rafariossaa , I'm not sure I completely understand what "...it would be easier just to start checking it in a linux machine", means.  How/why would it be easier to check "it" in a linux machine?

**Comment by rafariossaa** [comment]
Hi,
  Because we have had the experience that docker in windows has given problems with file system permissions.
  I would like to remove that facet from this issue by trying it on a linux machine.

**Comment by willim32533** [comment]
@rafariossaa Apologies for the delay in responding.  Would Ubuntu running on wsl2 qualify for the test scenario, or does it need to be a full-fledged VM?

**Comment by rafariossaa** [comment]
I would try it in an VM. Not sure what can happen in a wsl2 scenario.

**Comment by willim32533** [comment]
@rafariossaa I apologize for the delay, but I am (have been) waiting for the Linux VM to be created, which is handled by a different team.

**Comment by rafariossaa** [comment]
Hi,
  Don't worry. Come back when you have news.

**Comment by willim32533** [comment]
Thank you
