### ISSUE TITLE
Error while connection kafka with spark streaming

### ISSUE THREAD

**Issue by glcanvas** [bitnami/bitnami-docker-spark#61]
Hi! got error bellow while using your container: 
`Traceback (most recent call last):

  File "/opt/bitnami/spark/main.py", line 12, in <module>

    from pyspark.streaming.kafka import KafkaUtils

ModuleNotFoundError: No module named 'pyspark.streaming.kafka'`

my code
`sc = SparkContext("spark://spark:7077", "app")
ssc = StreamingContext(sc, 1)
stream = KafkaUtils.createStream(ssc, ["kafka:9092"], "logs", {"numtest": 1})
stream.pprint(100)`

**Comment by javsalgar** [comment]
Hi,

I was able to reproduce the issue. I will open a task for the engineering team to see how to make pyspark work out of the box in the Spark container. Thanks for reporting.

**Comment by OneCricketeer** [comment]
Add an en variable for `PYSPARK_SUBMIT_ARGS` that adds the spark-streaming kafka package. It's not included in this container, by default

**Comment by juan131** [comment]
Thanks for the suggestion @OneCricketeer ! We have an internal task in our backlog to investigate this issue, but please feel free to drop a PR if you came with a proposal to address it. We'll be glad to review it.

**Comment by OneCricketeer** [comment]
I don't really think a PR is necessary. Kaka packages can be added at runtime like so 

https://stackoverflow.com/a/70838796/2308683

**Comment by juan131** [comment]
That makes sense! I'll proceed to close this issue in this case, thanks so much for providing this useful information.
