### ISSUE TITLE
spark user write permissions broken in a particular shared volume configuration

### ISSUE THREAD

**Issue by willim32533** [bitnami/bitnami-docker-spark#69]
Docker compose that specify multiple shared volumes that have a common root folder and target unique subfolders (on the host) appear to break the spark user's write permissions; however, one shared volume that targets the root folder on the host and one shared volume that targets a subfolder of the same root folder also keep the spark user's write permissions in tact.

Multiple shared volumes that have no common root folder on the host appear to keep the spark user's write permissions in tact.

these two shared volume configurations are ok
`   volumes:`
`      - C:\spark_logs:/opt/bitnami/spark/logs`
`      - C:\sparklocalfiles\apps:/opt/bitnami/spark/hostapps`
`      - C:\edl:/opt/bitnami/spark/edl`
`      - C:\837\edl837json:/opt/bitnami/spark/sourcejsonfiles`

two shared volume version:
`   volumes:`
`      - C:\sparklocalfiles\logs:/opt/bitnami/spark/logs`
`      - C:\sparklocalfiles:/opt/bitnami/spark/hostfiles`

This configuration breaks the "spark" user's write permissions (they all have the same root folder on the host "sparklocalfiles")
`   volumes:`
`      - C:\sparklocalfiles\logs:/opt/bitnami/spark/logs`
`      - C:\sparklocalfiles\apps:/opt/bitnami/spark/hostapps`
`      - C:\sparklocalfiles\edl:/opt/bitnami/spark/edl`
`      - C:\sparklocalfiles\837\edl837json:/opt/bitnami/spark/sourcejsonfiles`

**Comment by javsalgar** [comment]
Hi,

It seems that you are using bind-mounted volumes in Docker for Windows. I'm afraid this is not a configuration we are actively testing. When using binded volumes, we always recommend to use the most open permissions as possible in order to avoid issues.

**Comment by willim32533** [comment]
The permissions on the folders of the host are wide open.  Thanks.
