### ISSUE TITLE
Different user contexts used for CLI spark-submit created executors vs native spark REST api

### ISSUE THREAD

**Issue by willim32533** [bitnami/bitnami-docker-spark#70]
When executing spark-submit via the CLI the executors are launched using the root user context, but spark-submit launched using the REST api uses the "spark" user.  Shouldn't these be using the same user?

Steps to reproduce:

- Enable the spark REST api service:

`spark.master.rest.enabled true` in local file named **spark-defaults.conf**. In the Dockerfile, specify root user in Dockerfile and do not revert back to USER 1001:

```Dockerfile
FROM bitnami/spark:latest
USER root

#copy that file into the image:
COPY SparkImage/spark-defaults.conf /opt/bitnami/spark/conf/

#expose the ports for the master
ENV SPARK_MASTER_PORT 7077
ENV SPARK_MASTER_WEBUI_PORT 8080
ENV SPARK_MASTER_RESTAPI_PORT 6066

EXPOSE ${SPARK_MASTER_WEBUI_PORT} 
EXPOSE ${SPARK_MASTER_PORT}
EXPOSE ${SPARK_MASTER_RESTAPI_PORT}
```

In the docker compose file include the following the spark master and specify `user: root` for the worker containers, too.

```yaml
    user: root
    ports:
      - '8080:8080'
      - '6066:6066'
      - '4040:4040'
```

Connect to the master container and launch the bash shell `docker exec -it spark-master /bin/bash`. Execute python job using spark-submit in client mode:

```bash
bin/spark-submit --master "spark://spark:7077" --deploy-mode "client" file:///opt/bitnami/spark/apps/myapp.py
```

The log file indicates the root user being used

> {"Event":"SparkListenerApplicationStart","App Name":"bronze837load","App ID":"local-1643401116243","Timestamp":1643401115320,"User":"root"}

Using curl (or Postman) execute the same python job via the REST api:

```console
$ curl -X POST http://spark-cluster-ip:6066/v1/submissions/create --header "Content-Type:application/json;charset=UTF-8" --data '{
{ "action": "CreateSubmissionRequest",
  "appArgs": [
    "file:///opt/bitnami/spark/apps/myapp.py"
  ],
 "appResource": "file:///opt/bitnami/spark/apps/myapp.py.py",
 "clientSparkVersion": "3.2.0",
 "environmentVariables": {
    "SPARK_ENV_LOADED": "1"
  },
 "mainClass": "org.apache.spark.deploy.SparkSubmit",
  "sparkProperties": {
    "spark.driver.supervise": "false",
    "spark.app.name": "Spark REST API - myapp.py",
    "spark.submit.deployMode": "client",
    "spark.master": "spark://spark:7077",
    "spark.eventLog.enabled":"true"
  }
}
```

The log indicates the spark user is being used:

> {"Event":"SparkListenerApplicationStart","App Name":"bronze837load","App ID":"local-1643725993890","Timestamp":1643725993146,"User":"spark"}

**Comment by juan131** [comment]
Hi @willim32533 

When you run the container as "root" it means that the container's entrypoint is executed as "root". However, the entrypoint could potentially launch other processes using a different system user (which is the case of this Bitnami Spark container). As you can see in the lines below, this container launches the Spark processes using the "spark" system user:

- https://github.com/bitnami/bitnami-docker-spark/blob/master/3/debian-10/rootfs/opt/bitnami/scripts/spark/run.sh#L29
- https://github.com/bitnami/bitnami-docker-spark/blob/master/3/debian-10/rootfs/opt/bitnami/scripts/libspark.sh#L62

This is the reason why you obtain `"User":"spark"` when posting the REST API. On the other hand, when you executed the `spark-submit` binary you were using the "root" user forcing `"User":"spark"`. You could try to run the command below to see that you'll obtain the same user you obtained when posting the API.

```bash
gosu spark /opt/bitnami/spark/bin/spark-submit --master "spark://spark:7077" --deploy-mode "client" file:///opt/bitnami/spark/apps/myapp.py
```

**Comment by willim32533** [comment]
Thank you.
