### ISSUE TITLE
How to configure the the history server to start when the master container starts

### ISSUE THREAD

**Issue by willim32533** [bitnami/bitnami-docker-spark#71]
In order to start the history server, the Apache Spark documentation indicates to execute the following: /sbin/start-history-server.sh.  Is it possible to configure a bitnami spark master container to automatically start the history server?

**Comment by javsalgar** [comment]
Hi,

In other containers we have an init scripts feature that allows to run custom modification to the container startup process. Would it make sense to your use case?

**Comment by willim32533** [comment]
I guess it would, but I don't want to break anything.  Is there an init script that can be edited on the spark 3.2.1 image?

**Comment by javsalgar** [comment]
Not that I can think of. I will create a task for adding that support in the container. I will let you know when I have more news.

**Comment by javsalgar** [comment]
Hi,

Could you provide more details in how to reproduce the issue?

**Comment by corico44** [comment]
Hi!

We just released a new revision of the chart. Now, we have an init scripts feature that allows to run custom modification to the container startup process.

I think this should cover your use case! 😄
