### ISSUE TITLE
Running Spark on YARN

### ISSUE THREAD

**Issue by kassio33** [bitnami/bitnami-docker-spark#75]
### Name and Version

bitnami/spark3

### What is the problem this feature will solve?

Hello
I'm a beginner who started learning sparks.
Thanks to the bitnami docker, it was easy to install.
How can I change standalone to yarn?
Thank you.

### What is the feature you are proposing to solve the problem?

I want to run Spark on YARN.
I'm sorry to leave a question here because I don't have a question menu.

**Comment by javsalgar** [comment]
Hi,

I'm afraid I'm not a Spark expert. Checking the bash code, I don't see any reference to YARN configuration. You would first need to check how this is configured by reading the upstream Spark documentation, and after that maybe mount a configuration file that enables this YARN mode.

**Comment by OneCricketeer** [comment]
Given that this is a Docker container, deploying Spark master in Kubernetes might make more sense.
