### ISSUE TITLE
(docs) Example setup with Jupyter

### ISSUE THREAD

**Issue by OneCricketeer** [bitnami/bitnami-docker-spark#77]
### Name and Version

bitnami/spark + bitnami/base-jupyter , latest

### What is the problem this feature will solve?

There are users who are deploying [Jupyter notebook container](https://github.com/bitnami/bitnami-docker-jupyter-base-notebook) and [installing Spark client into it](https://github.com/bitnami/bitnami-docker-jupyter-base-notebook/issues/2), while trying to connect to a Spark-Master (combining it with this repo, perhaps). 

[The Jupyter image requires Java for that to work](https://stackoverflow.com/questions/71678426/link-jupyterhub-with-spark-on-kubernetes).

### What is the feature you are proposing to solve the problem?

A user-guide to prevent misconfiguration.

**Comment by rafariossaa** [comment]
Hi,
  In this case, I think you could build your own images based on ours and add in what it is needed.
