### ISSUE TITLE
Shipping an environment to an executor installs it in /opt/bitnami/spark/work

### ISSUE THREAD

**Issue by janusqa** [bitnami/bitnami-docker-spark#88]
### Name and Version

docker.io/bitnami/spark:3.2.1

### What steps will reproduce the bug?

set the configuration to ship compressed virtual environment prepared with venv-pack
```

             (
                    "spark.archives",
                    "/opt/bitnami/spark/data/venv.tar.gz#/ovenv",
             ),

```
the environment is transferred and unzipped under `/opt/bitnami/spark/work` in a random directory like `app-20220621143354-0043 so there is no way beforehand to know how to set `PYSPARK_PYTHON` since the env is installed to some random location.

### What is the expected behavior?

if it is going to install it in the working directory then, install it to the directory right after the # sign which in my case is venv
so should be installed to `/opt/bitnami/spark/work/venv`

### What do you see instead?

`/opt/bitnami/spark/work/app-timestamp-incrementer/0/venv`

where random name is datestamp of current day hyphen then incrementing number

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami spark container image or Helm chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
