### ISSUE TITLE
Where Spark archive is coming from?

### ISSUE THREAD

**Issue by ebuildy** [bitnami/bitnami-docker-spark#90]
### Name and Version

bitnami/spark:v3.2.1

### What is the problem this feature will solve?

The official Apache Spark archive to download doesn't include AWS libraries, but bitnami Docker images yes.

It looks like the spark archive is coming from the bitnami catalog, but this is a complete black box to understand where is coming from?

### What is the feature you are proposing to solve the problem?

Use the official Apache Spark archive download

**Comment by carrodher** [comment]
I'm not sure if I'm understanding the question, could you please elaborate on what spark archive are you referring to?

**Comment by ebuildy** [comment]
I am refering to https://github.com/bitnami/bitnami-docker-spark/blob/master/3.3/debian-11/Dockerfile#L16

```
RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "spark" "3.3.0-1" --checksum ab23cac636be55578926379ca442ec25ae13db700b62bb7e82ed4537e19aeaa5
```

Where as official Spark release are coming from https://www.apache.org/dyn/closer.lua/spark/spark-3.2.1/spark-3.2.1-bin-hadoop3.2.tgz

**Comment by carrodher** [comment]
That tarball is the result of compiling the upstream source code and applying the Bitnami configuration to make it ready to work out of the box as a container image

**Comment by ebuildy** [comment]
thanks you, is it possible to see this process ? Our security team ask for it.

**Comment by rafariossaa** [comment]
Hi,
  It is not possible to see that process because it is integrated in our internal pipeline. We follow the procedure indicated here https://spark.apache.org/downloads.html including using that tar.gz
